### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by dantman** [Thuzi/facebook-node-sdk#106]
I've taken over maintenance of the `fb` module on npm. After I see if I can get GitHub to transfer issues to the [new repo](https://github.com/node-facebook/facebook-node-sdk) I'll publish 0.7.1-0.7.3 to npm.

This module has existed for some time and I think it's time for a 1.0.0 release. These are the items I have on the roadmap currently.
- [x] version option
- [x] default and customizable user-agent #17
- [x] better tests
- [x] beta tier? #76
- [x] update dependencies
- [x] Change `FB.api('4?fields=name', { fields: 'id,first_name' })` so it overrides fields instead of defining two query params.

If there are any other good candidates, please post.

**Comment by dantman** [comment]
I have released a `1.0.0-beta1` beta release of `fb` to npm.

It can be installed using either `npm install fb@next` or `npm install fb@^1.0.0-beta1`.

If possible I'd like people to try it out and comment on how it went.

**Comment by Joker666** [comment]
Has any api changed in your fb@next ? If it has, then is it fully documented? Should I be reporting issues to your new repo?

**Comment by dantman** [comment]
Yes, there have been some changes. Theoretically all non-breaking but you should tweak code anyways.

Among other things the new version the new version supports declaring what version of the FB API to use. Since users of `fb` are no longer stuck on the oldest version of the FB API their app has access to, it would be best to update code to work with the latest version (v2.4) of Facebook's API.

The whole API should be documented in the [README](https://github.com/node-facebook/facebook-node-sdk/blob/master/README.md), including some things that exist in 0.7.3 but weren't documented in the old README.

And yes, new issues would be best reported to the new repo. I cannot label, add milestones for, or close fixed issues in this repo.

**Comment by dantman** [comment]
1.0.1 has been published to npm
