### ISSUE TITLE
Question paging

### ISSUE THREAD

**Issue by bgnq** [Thuzi/facebook-node-sdk#111]
Hello,

With FB.api, I don't find where to put the paging token, can you help me please ?
On second parameter, I put an object with fields, but where put a paging token ?
Sample paging token : 
enc_AdAZBsCTaRDHNzVTaU2AJs2Yfhq4mQpk7lb4dK9vFFrRGs4XKzGQKxuyeoDQZBgtRKjVQvYMlVg5AD37QwmsfBUr2gxwZAZCYd0kEQhGQZCZAPwFWJ4QZDZD

Than you for your hep.

**Comment by dantman** [comment]
If you're talking about the token in `paging.cursors.after` described [here](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.5#cursors). The `next` url contains an `&after=` so it looks like the `after` field is what you use for pagination.

In the case of this SDK that means `FB.api('/...', {..., after: <paging token>}, cb)`.

**Comment by bgnq** [comment]
THANK YOU !! :)
