### ISSUE TITLE
Pagination Issue when calling FB.api with base url

### ISSUE THREAD

**Issue by whoyawn** [Thuzi/facebook-node-sdk#121]
Normally when you use pagination you call the next pages like this:

```
FB.api("/{id}/likes", function(response) {
  if (response.paging.next) {
    FB.api(response.paging.next);
  }
}
```

For my case, however, the second call returns an empty object with the id property as the url without the access token parameter.

In order to get around that, I have to trim the string:
```
FB.api("/v2.8/{id}/likes?access_token={token}&limit=25&after={cursor}",
          function(res) {
            console.log(res)
          })
...
```

which requires something like `string.replace("https://graph.facebook.com", "");`

Am I missing something? This doesn't seem like the optimal way of doing things.

**Comment by dantman** [comment]
Yes, the first parameter to `FB.api` is a path, not a url. The SDK is responsible for picking out the full URL. This should be the same for Facebook's own client-side JS SDK.

Note that for some API responses the Graph API also has non-url cursors available in the paging results.

Also, you're commenting on the dead Thuzi repo. The current version of this library is at: https://github.com/node-facebook/facebook-node-sdk

**Comment by whoyawn** [comment]
Thanks! I meant to comment in that one, I must have accidentally clicked on the old repo.
