### ISSUE TITLE
Can't reset access token in-state

### ISSUE THREAD

**Issue by individual11** [Thuzi/facebook-node-sdk#26]
Running something where I need to change the access token on the fly, but they way the code is, once it's set, it never looks for it again to change.

Something like this should do the trick

if(options('accessToken') && params.access_token != options('accessToken')) {
...etc

**Comment by prabirshrestha** [comment]
It is documented in README.md

> If you want to use the api compaitible with FB JS SDK, pass access_token as parameter.

``` js
FB.api('me', { fields: ['id', 'name'], access_token: 'access_token' }, function (res) {
    console.log(res);
}
```

Are you sure you are using this `facebook-node-sdk` (`npm install fb`)? There is no `params.access_token != options('accessToken')` comparison at all in our code.

**Comment by individual11** [comment]
It works fine using the example you provided. The error was occurring when I was using FB.setAccessToken('access_token'); ... it would never let me reset it to anything else once set.

The code I sent is not present in the code, it's a replacement I think it would solve the problem I found.

Thanks much.
