### ISSUE TITLE
posting images to event/album using graph api

### ISSUE THREAD

**Issue by swhamilton** [Thuzi/facebook-node-sdk#28]
This library is very useful, and I'm using it to post events on facebook through the api. I'd like to POST an image with the event, but doing this seems tricky...

The following curl command works for posting an event with an image (assuming the token has all the required permissions):

``` bash
curl -F 'access_token=<insertAccessToken>' \
-F 'name=Test Event 1' \
-F 'start_time=2013-01-20T12:00:00+0000' \
-F '@newImageName.png=@/Users/<mycomputer>/Sites/Node/facebook/image.png' \
http://graph.facebook.com/me/events
```

I found numerous people on stackoverflow.com looking for answers using the PHP facebook-sdk. Most seemed successful with both events and photos to albums: 
http://stackoverflow.com/questions/2718610/upload-photo-to-album-with-facebooks-graph-api

The key is setting the image as a separate multipart request and passing that in the POST. I assume this is what the curl -F '@newImageName.png=@/path//to/image.png'  does before POSTing the event. I want to achieve this multipart-formatting image post from my machine to FB using this library. 

This seems like a good start to adding this feature:
https://github.com/mscheibe/python-sdk/commit/13d5849eb0b54b9cda5cf03c35ea6df61094107e

I looked into the request.js library and it seems to support multipart posts also, I just don't know exactly how to go about implementing this. I might just end up adding the Node-Curl wrapper from https://github.com/chriso/curlrequest, but that seems a bit overkill.

Any help would be great.

**Comment by prabirshrestha** [comment]
This is a known issue.

Currently file uploading is not supported at all.

I have already implemented file uploads in facebook-csharp-sdk (https://github.com/facebook-csharp-sdk/facebook-csharp-sdk) so it isn't much of a problem. (It even supports uploading in files in batch requests, progress and cancellation, something that we would like to get in here too).

Feel free to send us a PR. :)

**Comment by swhamilton** [comment]
Speedy replies are awesome! Thanks for the info, so I don't go crazy trying to make it work. 

Unfortunately, i'm not familiar with C# so it would take a while to translate the code into JS.

I have concluded that request.js + node's fs do have the capabilities to read an image, format into multipart content type, and post. I will try working with this and see if there's a good way to implement this into this library.

also, found a library from this post (http://stackoverflow.com/questions/13797670/nodejs-post-request-multipart-form-data?rq=1) called Restler. might look into using this as an alternative to the request.js library (and relevant dependency node-form-data)

thanks again.

**Comment by sunojvijayan** [comment]
Uploading photos to albums is a good to have feature

**Comment by dantman** [comment]
@sunojvijayan File uploads support was added to the current repository for`fb` in `1.1.0`.

https://github.com/node-facebook/facebook-node-sdk#upload
