### ISSUE TITLE
Does not support images

### ISSUE THREAD

**Issue by randunel** [Thuzi/facebook-node-sdk#42]
When requesting an image, either an url or a buffer should be returned. Instead the JSON parser fails and returns an error.

`FB.api("/me/picture", {access_token: token}, cb);`

**Comment by prabirshrestha** [comment]
This is not a bug in the sdk. FB always returns a 302 redirect to an image when making an http request to `id/picture`.

Use fields parameter instead to get the picture.

``` js
FB.api('me/picture', { access_token: token, fields: ['picture']}, cb);
```
