### ISSUE TITLE
Managing Pages

### ISSUE THREAD

**Issue by albertvp** [Thuzi/facebook-node-sdk#43]
Hi, thanks for your module, is the best :+1: 

Once I have the user access tokens accepting the scope fields: publish_stream & manage_pages I don't have the extra tokens of their pages, Facebook says that is a Graph API step:

https://developers.facebook.com/docs/reference/api/page/#page_access_tokens

Do you have any example to get the extra access tokens of their admin pages?
Thank you,

best regards

**Comment by prabirshrestha** [comment]
Not a bug or feature request.

Please ask questions in stackoverflow and tag it with `facebook-node-sdk` and `facebook`. http://stackoverflow.com/questions/tagged/facebook-node-sdk
