### ISSUE TITLE
automatically add appsecret_proof to the request

### ISSUE THREAD

**Issue by prabirshrestha** [Thuzi/facebook-node-sdk#44]
Automatically add `appsecret_proof` to the request if `FacebookClient` contains `AppSecret` and the request contains `access_token`. 

https://developers.facebook.com/docs/reference/api/securing-graph-api/

**Comment by louisameline** [comment]
+1 Thank you :)

**Comment by louisameline** [comment]
Would a pull request be accepted for this ? It would probably be 4 or 5 lines.

**Comment by louisameline** [comment]
Done https://github.com/Thuzi/facebook-node-sdk/pull/61

**Comment by 9point6** [comment]
will this PR be accepted? I'd like to use this feature in my current project

**Comment by CRuppert** [comment]
This pr should be accepted at this point
