### ISSUE TITLE
500 FacebookApiException:

### ISSUE THREAD

**Issue by cmarrero01** [Thuzi/facebook-node-sdk#47]
I run the example, 

npm install
cd samples/scrumptious
npm install
node app.js

and I make click on the button login of facebook, an when retrieved from facebook, this is the error that showme.

500 FacebookApiException: {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100}}

This exactly happend with other libraries of facebook sdk, I don't know if is a bug of this library or if is some that I make wrong.

**Comment by prabirshrestha** [comment]
It is not a bug. You might want to check this issue for more info. You need to configure some stuffs before using it.

https://github.com/Thuzi/facebook-node-sdk/issues/41
