### ISSUE TITLE
Access Token Question

### ISSUE THREAD

**Issue by ScottBouloutian** [Thuzi/facebook-node-sdk#75]
```
var FB = require('fb');

FB.api('/v2.1/oauth/access_token', {
    client_id: 'id',
    client_secret: 'secret',
    grant_type: 'client_credentials'
}, function (res) {
    if(!res || res.error) {
        console.log(!res ? 'error occurred' : res.error);
        return;
    }

    var accessToken = res.access_token;
    FB.setAccessToken(accessToken);
    console.log(res);
});

FB.api('/v2.1/me/pokes', function (res) {
  if(!res || res.error) {
   console.log(!res ? 'error occurred' : res.error);
   return;
  }
});
```

Hi, I'm trying to make something like the above code work, but I can't seem to get the access token to be returned to me. When I log the accessToken value its just my client_secret appended to my client_id. This doesn't seem right. How do I get the above code to work as expected? Is this my fault or a bug with this repo?

**Comment by 3a4oT** [comment]
same question for me?

**Comment by ScottBouloutian** [comment]
So one thing I figured out is that I was wrong about it returning the client_secret appended to my  client_id. The access_token endpoint is successfully retuning my _application_ access token. The problem is, I'm not sure if this application access token can access /me/pokes or if I need a user access token. I'm thinking it's the later, but I'm not sure how to get that with this API.

**Comment by EwanValentine** [comment]
Same for me!
