### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by dantman** [Thuzi/facebook-node-sdk#78]
The newest version of this appears to be 0.7.3, however only 0.7.0 has been published to npm.

So if you `npm install fb` you get an old version with no appsecret_proof support.

**Comment by jarrodconnolly** [comment]
Seconded, please publish the latest to npm.

**Comment by joeltello** [comment]
yes the new appsecret_proof feature is nice

**Comment by dantman** [comment]
I have published 0.7.3 to npm.
