### ISSUE TITLE
handle JSONPARSE

### ISSUE THREAD

**Issue by M425** [Thuzi/facebook-node-sdk#89]
When I use 

``` javascript
FB.api('/me/picture' , {type: 'large', access_token: 'xxxxxxx'}, function(res) {
    console.log(res);
}
```

always returns 

```
{ error: { code: 'JSONPARSE', Error: [SyntaxError: Unexpected token �] } }
```

(using graph explorer everything work good)

**Comment by rurri** [comment]
Also get this error. Appears to be line 
302:                         json = JSON.parse(body);

The body in this case of /picture is not a JSON but an image.

body: GIF89a22�����������....

**Comment by rurri** [comment]
One possible solution to this would be to set 'followRedirect' on the request options to false. This would then retrieve the JSON data about the photo along with a url that could be used to fetch it.

**Comment by lemortel** [comment]
got the same error and maked me angry.
but i finally found the solution, you should set "redirect" to false.

``` javascript
  FB.api('/' + userid + '/picture', {redirect: false, access_token: appToken}, function (res) {
console.log(res);
}
```

ref: https://developers.facebook.com/docs/graph-api/reference/user/picture

**Comment by dbilenkin** [comment]
lemortel, you are a life saver! Thanks!

**Comment by dsc8x** [comment]
Thank you @lemortel, was having the exact same issue! :)
